# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4dd8786a124934597e96ef97b966452d572b142e5944b659a80c6a2243884f5ab3bcab8235335b419e992165522994e82a22d5c406d20b29fa89369733f2ed4a

test:
  secret_key_base: 1e5bec2904be4752f2638d0bdd1a964bbab3318e186561447c4854474ce4565c4b56d39ca2df8c6ff1c9bfb31f2e9cffd7b628ab50446124667a22c048690f1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
